stages:
  - deploy

build project:
  stage: deploy
  image: node:latest
  script:
    - npm install
    - npm run build
    - npm run export
    - npm install -g netlify-cli
    - netlify deploy --dir=out --prod
